services:
  postgres:
    image: postgres:16-alpine
    container_name: bee3ly-postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: bay3ly
      POSTGRES_PASSWORD: bay3ly
      POSTGRES_DB: bay3ly
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U bay3ly -d bay3ly']
      interval: 2s
      timeout: 5s
      retries: 15
    volumes:
      - bee3ly_pg_data:/var/lib/postgresql/data

volumes:
  bee3ly_pg_data:
